name: Railway Search Engine

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Internal Job ID'
        required: true
        type: string

      chat_id:
        description: 'Telegram Chat ID'
        required: true
        type: string

      username:
        description: 'Telegram Username'
        required: true
        type: string

      from_station:
        description: 'From'
        required: true
        type: string

      to_station:
        description: 'To'
        required: true
        type: string

      journey_date:
        description: 'Date'
        required: true
        type: string

      seat_class:
        description: 'Class Regex'
        required: true
        type: string

      desired_trains:
        description: 'Desired Trains'
        required: false
        default: 'ALL'
        type: string

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      # Public repository
      - name: Checkout public runner
        uses: actions/checkout@v4
        with:
          path: runner

      # Private repository
      - name: Checkout private core logic
        uses: actions/checkout@v4
        with:
          repository: Shuvo-924/RailwayTicketBotCore
          token: ${{ secrets.CORE_REPO_PAT }}
          path: core

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -f runner/Dockerfile \
            -t railway-search:latest \
            .

      # Run Docker container
      - name: Run Monitor
        env:
          CI: "true"

          JOB_ID: ${{ inputs.job_id }}
          CHAT_ID: ${{ inputs.chat_id }}
          USERNAME: ${{ inputs.username }}
          FROM_STATION: ${{ inputs.from_station }}
          TO_STATION: ${{ inputs.to_station }}
          JOURNEY_DATE: ${{ inputs.journey_date }}
          SEAT_CLASS: ${{ inputs.seat_class }}
          DESIRED_TRAINS: ${{ inputs.desired_trains }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          RAILWAY_PHONE: ${{ secrets.RAILWAY_PHONE }}
          RAILWAY_PASSWORD: ${{ secrets.RAILWAY_PASSWORD }}

        run: |
          docker run --rm \
            -e CI \
            -e JOB_ID \
            -e CHAT_ID \
            -e USERNAME \
            -e FROM_STATION \
            -e TO_STATION \
            -e JOURNEY_DATE \
            -e SEAT_CLASS \
            -e DESIRED_TRAINS \
            -e TELEGRAM_BOT_TOKEN \
            -e TELEGRAM_CHAT_ID \
            -e SUPABASE_URL \
            -e SUPABASE_KEY \
            -e FIREBASE_SERVICE_ACCOUNT \
            -e RAILWAY_PHONE \
            -e RAILWAY_PASSWORD \
            railway-search:latest